import Head from 'next/head'
import Style from './Home.module.scss'
import PostsHome from './Components/PostsHome/PostsHome'
import TopPosts from './Components/TopPosts/TopPosts'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Style.container}>
        <section className={Style.left}>
          <PostsHome />
        </section>

        <section className={Style.right}>
          <TopPosts />
        </section>
      </main>
    </div>
  )
}